spring.application.name=mvc-thymeleaft
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
spring.main.allow-circular-references=true
#server.servlet.session.cookie.max-age=0
server.servlet.session.timeout=300
